[package]
name = "flutter_rust_bridge_example_single_block_test"
version = "1.0.0"
edition.workspace = true

[lib]
name = "flutter_rust_bridge_example"
crate-type = ["cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = { workspace = true, features = [
  "chrono",
  "uuid",
] }

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
lazy_static = { workspace = true }
chrono = { workspace = true }
flutter_rust_bridge = { workspace = true, features = ["chrono", "uuid"] }
uuid = { workspace = true }
# wasm_thread = "0.2.0"

[dependencies.external-lib] # used for demo of external types mirroring
path = "./external"
package = "flutter_rust_bridge_example_external"
