[book]
authors = ["authors of flutter_rust_bridge, see GitHub README.md for detailed contributions"]
language = "en"
multilingual = false
src = "src"
title = "flutter_rust_bridge"

[preprocessor]

[preprocessor.links]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]

[output.linkcheck]
